apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: broker
  namespace: argocd
  labels:
    purpose: ngsild
spec:
  destination:
    namespace: broker
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cyclops/broker
    repoURL: https://github.com/cyclops-project/cyclops-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true