apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  labels:
    purpose: infra
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cyclops/sealed-secrets
    repoURL: https://github.com/cyclops-project/cyclops-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true