apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-server-block
  namespace: {{ $.Release.Namespace | quote }}
data:
  server-block.conf: |
    server {
      listen 0.0.0.0:8080;

      location / {
        return 200 "hello!";
      }

      location /ngsi-ld/ {
        proxy_pass http://data-service-scorpio:9090/ngsi-ld/;

        # Reject non-GET unless $allow_request = 1
        error_page 403 = @forbidden;

        if ($request_method != GET) {
          if ($allow_request = 0) {
            return 403;
          }
        }
      }

      location @forbidden {
        return 403 "Forbidden\n";
      }
    }