apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-main-config
data:
  nginx.conf: |
    env ALLOWED_HEADER_VALUE;

    worker_processes  1;
    events {
        worker_connections  1024;
    }
    http {
        include       mime.types;
        default_type  application/octet-stream;

        # Map sets $allow_request to 1 if header matches ALLOWED_HEADER_VALUE
        map $http_x_custom_header $allow_request {
            default 0;
            "${ALLOWED_HEADER_VALUE}" 1;
        }

        include /opt/bitnami/nginx/conf/server_blocks/*.conf;
    }