apiVersion: v1
kind: Secret
metadata:
  name: nginx-ngsi-ld-secret
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
stringData:
  ALLOWED_HEADER_VALUE: {{ randAlphaNum 30 | b64enc | quote }}