apiVersion: v2
name: broker
description: Chart for a simple broker
type: application
version: 1.0.0
dependencies:
  - name: scorpio-broker-aaio
    alias: scorpio
    condition: scorpio.enabled
    repository: https://fiware.github.io/helm-charts
    version: 0.4.7
  - name: postgresql
    alias: postgis
    condition: postgis.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.1.5
  - name: nginx
    version: 18.1.5
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
